services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Itx\DoctrineMigrations\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  migrationsDependencyFactory:
    class: Doctrine\Migrations\DependencyFactory
    factory: ['@Itx\DoctrineMigrations\DependencyFactory', 'createFactory']

  Doctrine\Migrations\Tools\Console\Command\DumpSchemaCommand:
    tags:
        - name: console.command
          command: 'migrations:dumpSchema'
          description: 'Dumps Schema'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'

  Doctrine\Migrations\Tools\Console\Command\ExecuteCommand:
    tags:
        - name: console.command
          command: 'migrations:execute'
          description: 'Executes Migration'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'

  Doctrine\Migrations\Tools\Console\Command\GenerateCommand:
    tags:
        - name: console.command
          command: 'migrations:generate'
          description: 'Generates new migration file'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'   

  Doctrine\Migrations\Tools\Console\Command\LatestCommand:
    tags:
        - name: console.command
          command: 'migrations:latest'
          description: 'Migrates to Latest Version'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'
      
  Doctrine\Migrations\Tools\Console\Command\ListCommand:
    tags:
        - name: console.command
          command: 'migrations:list'
          description: 'Lists Versions'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'   

  Doctrine\Migrations\Tools\Console\Command\MigrateCommand:
    tags:
        - name: console.command
          command: 'migrations:migrate'
          description: 'Migrate to specified version'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'     

  Doctrine\Migrations\Tools\Console\Command\RollupCommand:
    tags:
        - name: console.command
          command: 'migrations:rollup'
          description: ''
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'  

  Doctrine\Migrations\Tools\Console\Command\StatusCommand:
    tags:
        - name: console.command
          command: 'migrations:status'
          description: 'Shows the migration status'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory' 

  Doctrine\Migrations\Tools\Console\Command\SyncMetadataCommand:
    tags:
        - name: console.command
          command: 'migrations:syncMetadata'
          description: 'Syncs metadata'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'   

  Doctrine\Migrations\Tools\Console\Command\VersionCommand:
    tags:
        - name: console.command
          command: 'migrations:version'
          description: 'Shows the migrations version'
    arguments:
      $dependencyFactory: '@migrationsDependencyFactory'              
